import{invoke}from"@tauri-apps/api/core";import{isDesktopRuntime}from"./desktop";import type{NotificationRecord,QueueItem,SocialAccountRecord}from"../types/automation";import type{PlatformKey}from"../types/client";
const queueKey="socialflow.preview.queue.v1",accountKey="socialflow.preview.accounts.v1",notificationKey="socialflow.preview.notifications.v1",calendarKey="socialflow.preview.calendar.v1";const read=<T>(key:string):T[]=>{try{return JSON.parse(localStorage.getItem(key)??"[]");}catch{return[]}};const write=<T>(key:string,value:T[])=>localStorage.setItem(key,JSON.stringify(value));
export async function runSchedulerNow():Promise<number>{if(isDesktopRuntime())return invoke("run_scheduler_now");const calendar=read<any>(calendarKey);const queue=read<QueueItem>(queueKey);let processed=0;for(const item of calendar.filter((v:any)=>v.scheduledFor<=new Date().toISOString().slice(0,19)&&!queue.some(q=>q.scheduleId===v.scheduleId))){processed++;const account=read<SocialAccountRecord>(accountKey).find(a=>a.clientId===item.clientId&&a.platform===item.platform&&a.connectionStatus==="mock");const failed=account?.mockFailNext??false;queue.unshift({id:crypto.randomUUID(),scheduleId:item.scheduleId,postId:item.postId,clientId:item.clientId,clientName:item.clientName,platform:item.platform,title:item.title,caption:item.caption,scheduledFor:item.scheduledFor,timezone:item.timezone,status:failed?"retrying":"published",attempts:1,maxRetries:3,lastError:failed?"Simulated publishing failure":undefined,externalPostId:failed?undefined:`mock-${crypto.randomUUID()}`,updatedAt:new Date().toISOString()});if(failed&&account)write(accountKey,read<SocialAccountRecord>(accountKey).map(a=>a.id===account.id?{...a,mockFailNext:false}:a));}write(queueKey,queue);return processed;}
export async function listPublishingQueue(status="all"):Promise<QueueItem[]>{if(isDesktopRuntime())return invoke("list_publishing_queue",{status});const q=read<QueueItem>(queueKey);return status==="all"?q:q.filter(i=>i.status===status)}
export async function retryQueueItem(queueId:string){if(isDesktopRuntime())return invoke("retry_queue_item",{queueId});write(queueKey,read<QueueItem>(queueKey).map(i=>i.id===queueId?{...i,status:"retrying",lastError:undefined,updatedAt:new Date().toISOString()}:i));}
export async function cancelQueueItem(queueId:string){if(isDesktopRuntime())return invoke("cancel_queue_item",{queueId});write(queueKey,read<QueueItem>(queueKey).map(i=>i.id===queueId?{...i,status:"cancelled",updatedAt:new Date().toISOString()}:i));}
export async function publishNow(scheduleId:string){if(isDesktopRuntime())return invoke("publish_now",{scheduleId});const calendar=read<any>(calendarKey);write(calendarKey,calendar.map((i:any)=>i.scheduleId===scheduleId?{...i,scheduledFor:new Date().toISOString().slice(0,19)}:i));await runSchedulerNow();}
export async function listNotifications():Promise<NotificationRecord[]>{if(isDesktopRuntime())return invoke("list_notifications");return read(notificationKey)}export async function markNotificationRead(notificationId:string){if(isDesktopRuntime())return invoke("mark_notification_read",{notificationId});write(notificationKey,read<NotificationRecord>(notificationKey).map(n=>n.id===notificationId?{...n,isRead:true}:n));}
export async function listSocialAccounts(clientId?:string):Promise<SocialAccountRecord[]>{if(isDesktopRuntime())return invoke("list_social_accounts",{clientId});return read<SocialAccountRecord>(accountKey).filter(a=>!clientId||a.clientId===clientId)}
export async function connectMockAccount(clientId:string,clientName:string,platform:PlatformKey,accountName:string):Promise<string>{if(isDesktopRuntime())return invoke("connect_mock_account",{clientId,platform,accountName});const id=crypto.randomUUID();write(accountKey,[{id,clientId,clientName,platform,accountName:accountName||`${clientName} Mock`,connectionStatus:"mock",lastValidatedAt:new Date().toISOString(),mockFailNext:false},...read<SocialAccountRecord>(accountKey)]);return id;}
export async function disconnectAccount(accountId:string){if(isDesktopRuntime())return invoke("disconnect_account",{accountId});write(accountKey,read<SocialAccountRecord>(accountKey).map(a=>a.id===accountId?{...a,connectionStatus:"disconnected"}:a));}
export async function setMockFailure(accountId:string,failNext:boolean){if(isDesktopRuntime())return invoke("set_mock_failure",{accountId,failNext});write(accountKey,read<SocialAccountRecord>(accountKey).map(a=>a.id===accountId?{...a,mockFailNext:failNext}:a));}

export async function validateSocialAccount(accountId:string):Promise<void>{if(!isDesktopRuntime())throw new Error("Official account validation is available only in the macOS desktop app.");return invoke("validate_social_account",{accountId});}
export async function listSocialOAuthConfigurations():Promise<import("../types/automation").SocialOAuthConfiguration[]>{if(!isDesktopRuntime())return (["instagram","facebook","twitter","youtube"] as PlatformKey[]).map(platform=>({platform,available:false,connectionMethod:platform==="instagram"||platform==="facebook"?"broker":"browser_pkce",detail:"Secure official sign-in is available in the macOS desktop app."}));return invoke("list_social_oauth_configurations");}
export async function connectSocialAccountWithBrowser(clientId:string,platform:PlatformKey):Promise<import("../types/automation").BrowserOAuthResult>{if(!isDesktopRuntime())throw new Error("Secure official sign-in is available only in the macOS desktop app.");return invoke("connect_social_account_with_browser",{input:{clientId,platform}});}
