import { Copy, File, Film, Image as ImageIcon, LoaderCircle, MoreHorizontal, Plus, Search, Sparkles, Trash2, Upload, X } from "lucide-react";
import { useCallback,useEffect,useMemo,useRef,useState } from "react";
import { listClients,platformLabels } from "../services/clients";
import { deleteMedia,imagePromptForMedia,listMedia,mediaUrl,renameMedia,uploadMedia } from "../services/mediaLibrary";
import type { ClientSummary,PlatformKey } from "../types/client";
import type { MediaKind,MediaRecord } from "../types/media";

const kinds:MediaKind[]=["image","video","logo","brand_asset","creative","document"];
const bytes=(size:number)=>size>1024*1024?`${(size/1024/1024).toFixed(1)} MB`:`${Math.max(1,Math.round(size/1024))} KB`;
export function MediaLibraryPage(){
 const [clients,setClients]=useState<ClientSummary[]>([]);const[items,setItems]=useState<MediaRecord[]>([]);const[search,setSearch]=useState("");const[clientId,setClientId]=useState("");const[kind,setKind]=useState("all");const[loading,setLoading]=useState(true);const[error,setError]=useState("");const[uploadOpen,setUploadOpen]=useState(false);const[promptOpen,setPromptOpen]=useState(false);const[selected,setSelected]=useState<MediaRecord>();
 const refresh=useCallback(async()=>{setLoading(true);try{setItems(await listMedia({clientId:clientId||undefined,kind,search}));}catch(reason){setError(String(reason));}finally{setLoading(false);}},[clientId,kind,search]);
 useEffect(()=>{listClients({filter:"active",sort:"name"}).then(setClients);},[]);useEffect(()=>{const timer=setTimeout(()=>void refresh(),150);return()=>clearTimeout(timer);},[refresh]);
 const totals=useMemo(()=>({images:items.filter(i=>i.mimeType.startsWith("image/")).length,videos:items.filter(i=>i.mimeType.startsWith("video/")).length,size:items.reduce((sum,i)=>sum+i.fileSizeBytes,0)}),[items]);
 const remove=async(item:MediaRecord)=>{if(!confirm(`Delete ${item.fileName} from this Mac?`))return;try{await deleteMedia(item.id);setSelected(undefined);await refresh();}catch(reason){setError(String(reason));}};
 const rename=async(item:MediaRecord)=>{const name=prompt("New display name",item.fileName);if(!name)return;try{await renameMedia(item.id,name);await refresh();}catch(reason){setError(String(reason));}};
 return <div className="media-page"><section className="media-hero"><div><span>PHASE 6 · LOCAL ASSET STORAGE</span><h2>Media Library</h2><p>Images, videos, logos and creative assets stay on this Mac.</p></div><div className="media-stats"><span><b>{totals.images}</b> images</span><span><b>{totals.videos}</b> videos</span><span><b>{bytes(totals.size)}</b> local</span></div><button onClick={()=>setUploadOpen(true)}><Upload size={14}/> Upload media</button></section>
 {error&&<div className="studio-alert error"><span>{error}</span><button onClick={()=>setError("")}><X size={13}/></button></div>}
 <section className="media-toolbar panel"><label><Search size={13}/><input aria-label="Search media" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search media and tags"/></label><select value={clientId} onChange={e=>setClientId(e.target.value)}><option value="">All clients</option>{clients.map(c=><option key={c.id} value={c.id}>{c.clientName}</option>)}</select><select value={kind} onChange={e=>setKind(e.target.value)}><option value="all">All file types</option>{kinds.map(value=><option key={value} value={value}>{value.replaceAll("_"," ")}</option>)}</select><button className="secondary-button" onClick={()=>setPromptOpen(true)}><Sparkles size={13}/> Image Prompt Generator</button></section>
 {loading?<div className="media-empty"><LoaderCircle className="spin"/> Loading local media…</div>:items.length===0?<div className="media-empty panel"><div><ImageIcon size={25}/></div><h3>Your local media library is ready</h3><p>Upload brand assets or create an image prompt for ChatGPT. No image API key is needed.</p><button onClick={()=>setUploadOpen(true)}><Plus size={13}/> Upload first asset</button></div>:<section className="media-grid">{items.map(item=><article className="panel" key={item.id} onClick={()=>setSelected(item)}><div className="media-thumb">{item.mimeType.startsWith("image/")?<img src={mediaUrl(item)} alt={item.fileName}/>:item.mimeType.startsWith("video/")?<video src={mediaUrl(item)} aria-label={`${item.fileName} video preview`} muted playsInline preload="metadata"/>:<File size={24}/>}<b>{item.kind.replaceAll("_"," ")}</b></div><div className="media-meta"><h3>{item.fileName}</h3><p>{item.clientName??"Shared library"} · {bytes(item.fileSizeBytes)}</p><div>{item.tags.slice(0,3).map(tag=><span key={tag}>{tag}</span>)}</div></div><button aria-label="Media actions"><MoreHorizontal size={14}/></button></article>)}</section>}
 {selected&&<div className="media-drawer"><header><div><span>ASSET DETAILS</span><h3>{selected.fileName}</h3></div><button onClick={()=>setSelected(undefined)}><X size={15}/></button></header><div className="media-drawer-preview">{selected.mimeType.startsWith("image/")?<img src={mediaUrl(selected)} alt={selected.fileName}/>:selected.mimeType.startsWith("video/")?<video src={mediaUrl(selected)} aria-label={`${selected.fileName} video player`} controls playsInline preload="metadata"/>:<Film size={34}/>}</div><dl><div><dt>Client</dt><dd>{selected.clientName??"Shared"}</dd></div><div><dt>Type</dt><dd>{selected.kind}</dd></div><div><dt>Size</dt><dd>{bytes(selected.fileSizeBytes)}</dd></div><div><dt>Platforms</dt><dd>{selected.platforms.map(p=>platformLabels[p]).join(", ")||"Any"}</dd></div></dl><footer><button onClick={()=>void rename(selected)}>Rename</button><button className="danger" onClick={()=>void remove(selected)}><Trash2 size={12}/> Delete</button></footer></div>}
 {uploadOpen&&<UploadModal clients={clients} onClose={()=>setUploadOpen(false)} onDone={()=>{setUploadOpen(false);void refresh();}}/>}{promptOpen&&<PromptModal clients={clients} onClose={()=>setPromptOpen(false)}/>}</div>;
}
function UploadModal({clients,onClose,onDone}:{clients:ClientSummary[];onClose:()=>void;onDone:()=>void}){const input=useRef<HTMLInputElement>(null);const[file,setFile]=useState<File>();const[clientId,setClientId]=useState("");const[kind,setKind]=useState<MediaKind>("image");const[tags,setTags]=useState("");const[platforms,setPlatforms]=useState<PlatformKey[]>([]);const[busy,setBusy]=useState(false);const[error,setError]=useState("");const save=async()=>{if(!file)return setError("Choose a file first.");setBusy(true);try{await uploadMedia(file,{clientId:clientId||undefined,kind,tags:tags.split(",").map(v=>v.trim()).filter(Boolean),platforms});onDone();}catch(reason){setError(String(reason));}finally{setBusy(false);}};return <div className="studio-prompt-backdrop"><section className="media-modal"><header><div><span>LOCAL UPLOAD</span><h3>Add media to this Mac</h3></div><button onClick={onClose}><X size={15}/></button></header><div className="media-upload-form">{error&&<p className="media-form-error">{error}</p>}<button className="media-drop" onClick={()=>input.current?.click()}><Upload size={21}/><strong>{file?.name??"Choose image, video or brand asset"}</strong><small>{file?bytes(file.size):"Up to 500 MB · stored in app data"}</small></button><input hidden ref={input} type="file" accept="image/*,video/*,.pdf" onChange={e=>setFile(e.target.files?.[0])}/><label><span>Client</span><select value={clientId} onChange={e=>setClientId(e.target.value)}><option value="">Shared library</option>{clients.map(c=><option key={c.id} value={c.id}>{c.clientName}</option>)}</select></label><label><span>Asset type</span><select value={kind} onChange={e=>setKind(e.target.value as MediaKind)}>{kinds.map(k=><option key={k} value={k}>{k.replaceAll("_"," ")}</option>)}</select></label><label className="wide"><span>Tags</span><input value={tags} onChange={e=>setTags(e.target.value)} placeholder="coffee, weekend, campaign"/></label><div className="media-platform-choice">{(["instagram","facebook","twitter","youtube"] as PlatformKey[]).map(p=><button key={p} className={platforms.includes(p)?"selected":""} onClick={()=>setPlatforms(current=>current.includes(p)?current.filter(v=>v!==p):[...current,p])}>{platformLabels[p]}</button>)}</div></div><footer><span>Files never leave this Mac.</span><button disabled={busy} onClick={()=>void save()}>{busy?<LoaderCircle className="spin" size={13}/>:<Upload size={13}/>} Upload</button></footer></section></div>}
function PromptModal({clients,onClose}:{clients:ClientSummary[];onClose:()=>void}){const[client,setClient]=useState("");const[purpose,setPurpose]=useState("");const[style,setStyle]=useState("");const[platforms,setPlatforms]=useState<string[]>(["Instagram"]);const output=imagePromptForMedia(clients.find(c=>c.id===client)?.brandName||"My brand",purpose,platforms,style);return <div className="studio-prompt-backdrop"><section className="media-modal prompt"><header><div><span>NO IMAGE API</span><h3>Image Prompt Generator</h3></div><button onClick={onClose}><X size={15}/></button></header><div className="media-prompt-grid"><div><label>Client<select value={client} onChange={e=>setClient(e.target.value)}><option value="">Choose client</option>{clients.map(c=><option key={c.id} value={c.id}>{c.clientName}</option>)}</select></label><label>Purpose<input value={purpose} onChange={e=>setPurpose(e.target.value)} placeholder="Weekend coffee promotion"/></label><label>Visual style<input value={style} onChange={e=>setStyle(e.target.value)} placeholder="Warm editorial photography"/></label></div><pre>{output}</pre></div><footer><span>Paste into ChatGPT, then upload the result.</span><button onClick={()=>void navigator.clipboard.writeText(output)}><Copy size={13}/> Copy Image Prompt</button></footer></section></div>}
